config/routes.rb
Rails.application.routes.draw do
  root "books#index"

  resources :books, only: [:index, :show] do 
    resources :reviews, only: [:new, :create]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord


  has_many :reviews

  validates :title, presence: true
  validates :author, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :book
  # validates :book_id, presence: true

  validates :rating, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index 

        @books = Book.all
        # render /books/index.html.erb
    end

    def show 
        @book = Book.find(params[:id])
        @reviews = @book.reviews
    end



end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def new 
       @book = Book.find(params[:book_id])

       @review = Review.new
    end

    def create 
        @book = Book.find(params[:book_id])
        @review = Review.new(review_params)

        @review.book_id = @book.id

        if @review.save    
            flash[:success] = "you did it! Im proud of you!"
            redirect_to book_path(@book)
        else 
            flash.now[:banana] = @review.errors.full_messages.to_sentence
            render :new
        end

    end

    private 

    def review_params 
        params.require(:review).permit(:rating, :body)
    end

 
end

app/views/books/index.html.erb
<h1>Books</h1>

<% @books.each do |book| %>
<li>
   <%= link_to book.title, book_path(book)  %>
</li>

<% end %>

app/views/books/new.html.erb
<h2> New Book Page (if we have time) </h2>

app/views/books/show.html.erb
<h1> Title: <%= @book.title %> </h1>
<h2> Author: <%= @book.author %> </h2>
<p> ISBN: <%= @book.isbn %> </p>


<% @reviews.each do |review| %>

    <li>
        Rating: <%= review.rating %> | What they said: <%= review.body %>
    </li>

<% end %>

<%= link_to 'Add a Review', new_book_review_path(@book) %>

app/views/homes/index.html.erb
<div id="app">

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>React on Rails</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/reviews/new.html.erb
<h1>Review form for <%= @book.title %></h1>

<%= form_for [@book, @review]  do |f| %>
    <%= f.label :rating %>
    <%= f.text_field :rating %>

    <%= f.label(:body, "Review") %>
    <%= f.text_field :body %>

    <%= f.submit("Add Review") %>
<% end %>